### ISSUE TITLE
Request for license

### ISSUE THREAD

**Issue by stuartsierra** [arohner/arohner-utils#1]
Hello,

I am working with a project using [clj-r53](https://github.com/arohner/clj-r53), so thanks for publishing that!

I came across `arohner-utils` during a license audit of this project's dependencies, and found that it doesn't have a declared license.

To facilitate our participation external reviews, we would appreciate it if you could add `:license` metadata to the project.clj file or a LICENSE file in the repository.

Thank you.

**Comment by arohner** [comment]
Fixed in https://github.com/arohner/arohner-utils/commit/b477f0af0e43135f561c4be0e33d0512f65db9ea

**Comment by stuartsierra** [comment]
Thanks!
